<?php
if ($this->getFacebookPixelID()) {
  $eventId = \Facebook\BusinessExtension\Helper\EventIdGenerator::guidv4();
  $this->trackServerEvent($eventId);
?>
<script>
  fbq('track', 'ViewContent', {
    source: "<?php echo $this->getSource() ?>",
    version: "<?php echo $this->getMagentoVersion() ?>",
    pluginVersion: "<?php echo $this->getPluginVersion() ?>",
    content_type: "<?php echo $this->getContentType() ?>",
    content_ids: [<?php echo $this->getContentIDs() ?>]
    <?php if ($this->getContentName()) { ?>
      , content_name: "<?php echo $this->getContentName() ?>"
    <?php } ?>
    <?php if ($this->getContentCategory()) { ?>
      , content_category: "<?php echo $this->getContentCategory() ?>"
    <?php } ?>
    <?php if ($this->getValue() && $this->getCurrency()) { ?>
      , value: <?php echo $this->getValue() ?>
      , currency: "<?php echo $this->getCurrency() ?>"
    <?php } ?>
    }
    ,{
      eventID:  "<?php echo $eventId ?>"
    }
  );
</script>
<?php $this->logEvent($this->getFacebookPixelID(), 'ViewContent') ?>
<?php } ?>
