<?php if ($this->getFacebookPixelID() && $this->shouldFireAddToCart()) { ?>
  <script>
    fbq('track', 'AddToCart', {
      source: 'magento',
      version: "<?php echo $this->getMagentoVersion() ?>",
      pluginVersion: "<?php echo $this->getPluginVersion() ?>",
      content_type: "<?php echo $this->getContentType() ?>",
      content_ids: [<?php echo $this->getContentIDs() ?>]
      <?php if ($this->getContentName()) { ?>
        , content_name: "<?php echo $this->getContentName() ?>"
      <?php } ?>
      <?php if ($this->getContentCategory()) { ?>
        , content_category: "<?php echo $this->getContentCategory() ?>"
      <?php } ?>
      <?php if ($this->getValue() && $this->getCurrency()) { ?>
        , value: <?php echo $this->getValue() ?>
      <?php } ?>
      <?php if ($this->getValue() && $this->getCurrency()) { ?>
        , currency: "<?php echo $this->getCurrency() ?>"
      <?php } ?>
    });
  </script>
<?php } ?>
