<?php if ($this->isMessengerChatPluginEnabled()) {?>
<!-- Facebook JSSDK -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId            : '',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : '<?php echo $this->getFacebookJSSDKVersion() ?>'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<div
  class="fb-customerchat"
  attribution="fbe_magento"
  page_id="<?php echo $this->getFacebookPageID() ?>"
/>
<?php }?>
